blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Maximus-Technologies-Uganda/training-prince/discussions
    about: Please ask and answer questions here.
